[package]
name = "shader"
version.workspace = true
edition.workspace = true
license.workspace = true
# repository.workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = "0.9"
voxtree = { version = "0.1.4", default-features = false }
shared = { path = "../shared" }
