[package]
name = "shared"
version.workspace = true
edition.workspace = true
license.workspace = true
# repository.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
bytemuck = { version = "1.6.3", features = ["derive"] }
# spirv-std = "0.9"
